import type { Student } from "@/components/students/student-data-table"

// Mock data for demonstration
export const mockStudents: Student[] = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@school.com",
    studentId: "STU001",
    class: "Class 10A",
    grade: "A",
    attendance: 95,
    status: "active",
    phone: "+1234567890",
    address: "123 Main St, City, State",
    parentName: "Jane Doe",
    parentPhone: "+1234567891",
    enrollmentDate: "2023-09-01",
  },
  {
    id: "2",
    firstName: "Alice",
    lastName: "Smith",
    email: "alice.smith@school.com",
    studentId: "STU002",
    class: "Class 10B",
    grade: "B",
    attendance: 88,
    status: "active",
    phone: "+1234567892",
    address: "456 Oak Ave, City, State",
    parentName: "Bob Smith",
    parentPhone: "+1234567893",
    enrollmentDate: "2023-09-01",
  },
  {
    id: "3",
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@school.com",
    studentId: "STU003",
    class: "Class 9A",
    grade: "A",
    attendance: 92,
    status: "active",
    phone: "+1234567894",
    address: "789 Pine St, City, State",
    parentName: "Sarah Johnson",
    parentPhone: "+1234567895",
    enrollmentDate: "2023-09-01",
  },
  {
    id: "4",
    firstName: "Emily",
    lastName: "Brown",
    email: "emily.brown@school.com",
    studentId: "STU004",
    class: "Class 9B",
    grade: "C",
    attendance: 75,
    status: "active",
    phone: "+1234567896",
    address: "321 Elm St, City, State",
    parentName: "David Brown",
    parentPhone: "+1234567897",
    enrollmentDate: "2023-09-01",
  },
  {
    id: "5",
    firstName: "David",
    lastName: "Wilson",
    email: "david.wilson@school.com",
    studentId: "STU005",
    class: "Class 11A",
    grade: "A",
    attendance: 98,
    status: "active",
    phone: "+1234567898",
    address: "654 Maple Ave, City, State",
    parentName: "Lisa Wilson",
    parentPhone: "+1234567899",
    enrollmentDate: "2022-09-01",
  },
  {
    id: "6",
    firstName: "Sarah",
    lastName: "Davis",
    email: "sarah.davis@school.com",
    studentId: "STU006",
    class: "Class 11B",
    grade: "B",
    attendance: 82,
    status: "inactive",
    phone: "+1234567800",
    address: "987 Cedar St, City, State",
    parentName: "Mark Davis",
    parentPhone: "+1234567801",
    enrollmentDate: "2022-09-01",
  },
  {
    id: "7",
    firstName: "James",
    lastName: "Miller",
    email: "james.miller@school.com",
    studentId: "STU007",
    class: "Class 12A",
    grade: "A",
    attendance: 96,
    status: "active",
    phone: "+1234567802",
    address: "147 Birch Rd, City, State",
    parentName: "Anna Miller",
    parentPhone: "+1234567803",
    enrollmentDate: "2021-09-01",
  },
  {
    id: "8",
    firstName: "Jessica",
    lastName: "Garcia",
    email: "jessica.garcia@school.com",
    studentId: "STU008",
    class: "Class 12B",
    grade: "C",
    attendance: 70,
    status: "suspended",
    phone: "+1234567804",
    address: "258 Spruce Ln, City, State",
    parentName: "Carlos Garcia",
    parentPhone: "+1234567805",
    enrollmentDate: "2021-09-01",
  },
  {
    id: "9",
    firstName: "Christopher",
    lastName: "Martinez",
    email: "christopher.martinez@school.com",
    studentId: "STU009",
    class: "Class 8A",
    grade: "B",
    attendance: 85,
    status: "active",
    phone: "+1234567806",
    address: "369 Willow Dr, City, State",
    parentName: "Maria Martinez",
    parentPhone: "+1234567807",
    enrollmentDate: "2024-09-01",
  },
  {
    id: "10",
    firstName: "Ashley",
    lastName: "Anderson",
    email: "ashley.anderson@school.com",
    studentId: "STU010",
    class: "Class 8B",
    grade: "A",
    attendance: 94,
    status: "active",
    phone: "+1234567808",
    address: "741 Poplar St, City, State",
    parentName: "Robert Anderson",
    parentPhone: "+1234567809",
    enrollmentDate: "2024-09-01",
  },
]
